environment:
  matrix:
    - MSYSTEM: MINGW64
      MSYS_ARCH: "x86_64"
      ARCH: "64bit"

    - MSYSTEM: MINGW32
      MSYS_ARCH: "i686"
      ARCH: "32bit"

branches:
  only:
    - master

clone_depth: 1

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
  - del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll
  # Temporary fix until appveyor updates its msys build https://github.com/msys2/MINGW-packages/issues/5437
  - C:\msys64\usr\bin\pacman -Rdd mingw-w64-i686-ncurses mingw-w64-i686-termcap mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-objc --noconfirm --noprogressbar
  - C:\msys64\usr\bin\pacman -Rdd mingw-w64-x86_64-ncurses mingw-w64-x86_64-termcap mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-objc --noconfirm --noprogressbar
  
  - C:\msys64\usr\bin\pacman -Syuu --needed --noconfirm --noprogressbar --overwrite \\*
  - ps: |
        $env:TIME_STRING=(get-date -UFormat "%Y-%m-%d").ToString()
        $env:BUILDROOT="C:\msys64\home\appveyor\gajim\win\_build_root"

        function bash($command) {
          Write-Host $command -NoNewline
          C:\msys64\usr\bin\sh.exe --login -c $command
        }

        bash "git clone C:/projects/gajim C:/msys64/home/appveyor/gajim"
        bash "C:/msys64/home/appveyor/gajim/win/build.sh $($env:MSYS_ARCH)"
        Push-AppveyorArtifact "$($env:BUILDROOT)/Gajim.exe" -FileName "Gajim-Master-$($env:ARCH)-$($env:TIME_STRING).exe"
        Push-AppveyorArtifact "$($env:BUILDROOT)/Gajim-Portable.exe" -FileName "Gajim-Portable-Master-$($env:ARCH)-$($env:TIME_STRING).exe"

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

deploy:
    # FTP deployment provider settings
  - provider: FTP
    protocol: ftp
    host: panoramix.gajim.org
    username:
      secure: SNcOJDhUtBjfddbKXudE2w==
    password:
      secure: tQkYbcUb6nChCp0cdqo4CA==
    folder: win_snap
    active_mode: false
    beta: true      # enable alternative FTP library for 'ftp' and 'ftps' modes
    debug: true
